In [65]:
import pymetis
import numpy as np
import networkx as nx
import os
import math
import time

In [43]:
f = open("data/fb-pages-politician.edges",encoding='utf-8')

In [44]:
contents = f.readline()
dict = {}
while contents:
    contents = contents[:-1]
    nodes = contents.split(',')
    node1 = int(nodes[0])
    node2 = int(nodes[1])
    if dict.get(node1, None) is None:
        tmp = [node2]
        dict[node1] = tmp
    else:
        dict[node1].append(node2)
    if dict.get(node2,None) is None:
        tmp2 = [node1]
        dict[node2] = tmp2
    else:
        dict[node2].append(node1)
    contents = f.readline()

adj = []
idx = -1
for key in dict:
    idx = max(idx,key)

for i in range(0,idx+1):
    if dict.get(i,None) is None:
        adj.append([])
    else:
        adj.append(dict.get(i,None))

In [49]:
(edgecuts,parts) = pymetis.part_graph(nparts=3,adjacency=adj)

In [69]:
maxParts = 200
vector = None
start = time.time()
for parts in range(2,math.ceil(maxParts)):
    (edgecuts,pm) = pymetis.part_graph(nparts=parts,adjacency=adj)
    tmp = np.zeros((idx+1,parts))
    for i in range(0,len(pm)):
        ix = pm[i]
        tmp[i][ix] = 1
    if vector is None:
        vector = tmp
    else:
        vector = np.append(vector,tmp,axis=1)

end = time.time()
print(end-start,'s')

27.581152200698853 s


In [71]:
vector

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [54]:

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[0,0,0],[0,0,0]])
c = np.insert(a, 0, values=b, axis=0)
d = np.insert(a, len(a), values=b, axis=1)
print(c)
print(d)

[[0 0 0]
 [0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 0 0]
 [4 5 6 0 0]
 [7 8 9 0 0]]
